[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "opencv-python",
    "pandas",
    "pillow",
    "plotly",
    "pydantic",
    "pymupdf",
    "pytesseract",
    "pytest",
    "streamlit>=1.47.0",
]
